# Generated by Django 3.1.5 on 2021-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210129_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='tag',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('repo', models.ManyToManyField(blank=True, related_name='tag', to='network.Repo')),
            ],
        ),
    ]
