# Generated by Django 3.1.5 on 2021-01-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210130_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='repo',
        ),
    ]
