# Generated by Django 3.1.5 on 2021-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_tag_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='tags', to='network.Repo'),
        ),
    ]
