# Generated by Django 3.1.5 on 2021-02-01 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_tag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repo',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
