# Generated by Django 3.1.5 on 2021-02-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20210201_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
