# Generated by Django 3.1.5 on 2021-02-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210201_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
