# Generated by Django 3.1.5 on 2021-02-07 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210202_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='user',
        ),
        migrations.AddField(
            model_name='repo',
            name='user',
            field=models.ManyToManyField(related_name='repos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
