# Generated by Django 3.1.5 on 2021-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20210216_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
