# Generated by Django 3.1.5 on 2021-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20210216_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
