# Generated by Django 3.1 on 2020-08-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='pescador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quem_foi_para_mar_core.pescador'),
        ),
    ]
