# Generated by Django 3.1 on 2020-08-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0003_auto_20200811_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='pescador_id',
            new_name='pescador',
        ),
    ]
