# Generated by Django 3.1 on 2020-08-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0007_remove_viagem_pescador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='pescador_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quem_foi_para_mar_core.pescador'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='pescador_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quem_foi_para_mar_core.pescador'),
        ),
    ]
