# Generated by Django 3.1 on 2020-08-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0009_auto_20200811_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='pescador_id',
        ),
    ]
