# Generated by Django 3.1 on 2020-08-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0011_contato_pescador_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='embarcacao',
            options={'verbose_name_plural': 'Embarcações'},
        ),
        migrations.AlterModelOptions(
            name='pescador',
            options={'verbose_name_plural': 'Pescadores'},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='pescador_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quem_foi_para_mar_core.pescador'),
        ),
    ]
