# Generated by Django 3.1 on 2020-08-15 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0012_auto_20200812_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescador',
            name='senha',
            field=models.CharField(default=0, max_length=50, validators=[django.core.validators.MinLengthValidator], verbose_name='Senha'),
        ),
    ]
