# Generated by Django 3.1 on 2020-08-15 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0013_pescador_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator], verbose_name='Senha')),
            ],
        ),
        migrations.RemoveField(
            model_name='pescador',
            name='senha',
        ),
    ]
