# Generated by Django 3.1 on 2020-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0014_auto_20200815_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
