# Generated by Django 3.1 on 2020-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0015_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescador',
            name='contato',
            field=models.CharField(default=0, max_length=150, verbose_name='Contato em terra(nome e telefone)'),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
