# Generated by Django 3.1 on 2020-08-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quem_foi_para_mar_core', '0016_auto_20200815_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='embarcacao_retornou',
        ),
    ]
