export const FETCH_BIRTHDAYS = 'FETCH_BIRTHDAYS';
export const FETCH_BIRTHDAYS_SUCCESS = 'FETCH_BIRTHDAYS_SUCCESS';
export const ADD_BIRTHDAY = 'FETCH_BIRTHDAYS_SUCCESS';
export const ADD_BIRTHDAY_SUCCESS = 'FETCH_BIRTHDAYS_SUCCESS';
