//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gerenciador_hashtags_twitter.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gerenciador_hashtags_twitter.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hashtag name cannot be null..
        /// </summary>
        internal static string HashtagCannotBeNull {
            get {
                return ResourceManager.GetString("HashtagCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hashtag id seems to be invalid..
        /// </summary>
        internal static string InvalidHashtagId {
            get {
                return ResourceManager.GetString("InvalidHashtagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publish date seems to be invalid..
        /// </summary>
        internal static string InvalidPublishDate {
            get {
                return ResourceManager.GetString("InvalidPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwordHash cannot be null..
        /// </summary>
        internal static string PasswordHashInvalid {
            get {
                return ResourceManager.GetString("PasswordHashInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author cannot be null..
        /// </summary>
        internal static string TweetAuthorCannotBeNull {
            get {
                return ResourceManager.GetString("TweetAuthorCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message cannot be null..
        /// </summary>
        internal static string TweetMessageCannotBeNull {
            get {
                return ResourceManager.GetString("TweetMessageCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message must have a Hashtag..
        /// </summary>
        internal static string TweetMessageMustHaveHashtag {
            get {
                return ResourceManager.GetString("TweetMessageMustHaveHashtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id is invalid..
        /// </summary>
        internal static string UserIdIsInvalid {
            get {
                return ResourceManager.GetString("UserIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username cannot be null..
        /// </summary>
        internal static string UsernameCannotBeNull {
            get {
                return ResourceManager.GetString("UsernameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be only number and letters..
        /// </summary>
        internal static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
    }
}
