export const FETCH_BIRTHDAYS = 'FETCH_BIRTHDAYS';
export const FETCH_BIRTHDAYS_SUCCESS = 'FETCH_BIRTHDAYS_SUCCESS';
export const FETCH_BIRTHDAYS_ERROR = 'FETCH_BIRTHDAYS_ERROR';

export const BIRTHDAY_FORM_SET_FIELD = 'BIRTHDAY_FORM_SET_FIELD';
export const BIRTHDAY_FORM_SET_ERROR = 'BIRTHDAY_FORM_SET_ERROR';
export const BIRTHDAY_FORM_RESET = 'BIRTHDAY_FORM_RESET';
export const BIRTHDAY_FORM_SUBMIT = 'BIRTHDAY_FORM_SUBMIT';
export const BIRTHDAY_FORM_SUBMIT_SUCCESS = 'BIRTHDAY_FORM_SUBMIT_SUCCESS';
export const BIRTHDAY_FORM_SUBMIT_ERROR = 'BIRTHDAY_FORM_SUBMIT_ERROR';
